# Generated by Django 2.1.7 on 2019-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default=None, max_length=300)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('ponentes', models.CharField(max_length=300)),
                ('concepto_pago', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Eventos2',
            },
        ),
    ]
